name: Unit Testing and Deployment

on:
  pull_request:
    branches:
      - test
    types: [closed]

jobs:
  unit_test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest test.py

      - name: Merge to main and deploy
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'test'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin main
          # Trigger Jenkins job for containerization and deployment to Docker Hub
          # Insert Jenkins job trigger command here

      - name: Create pull request to main
        if: success()
        run: |
          gh pr create --base main --head test --title "Merge changes to main"
